---
chart_ref: traefik/traefik
chart_repository_name: traefik
chart_version: "25.0.0"
helm_repo_pass: "{{ undef() }}"
helm_repo_url: https://traefik.github.io/charts
helm_repo_user: "{{ undef() }}"
k8s_config: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_KUBECONFIG', default=undef()) }}"
k8s_context: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_CONTEXT', default=undef()) }}"
k8s_namespace: traefik
# -- Additional containers (e.g. for metric offloading sidecars)
traefik_additional_containers: []
traefik_check_new_version: false
traefik_dashboard: true
traefik_dashboard_fqdn: ""
traefik_dashboard_pass: admin
traefik_dashboard_user: admin
# -- Additional deployment annotations (e.g. for jaeger-operator sidecar injection)
traefik_deploy_annotations: { }
# -- Additional deployment labels (e.g. for filtering deployment by custom labels)
traefik_deploy_labels: { }
traefik_headers_browser_xss_filter: true    # X-XSS-Protection=1; mode=block
traefik_headers_content_type_nosniff: true    # X-Content-Type-Options=nosniff
traefik_headers_frame_deny: true    # X-Frame-Options=deny
traefik_headers_referrer_policy: "strict-origin-when-cross-origin"
traefik_headers_ssl_redirect: false    # Allow only https requests
# Add the Strict-Transport-Security header even when the connection is HTTP
traefik_headers_sts_force: false
# Add includeSubdomains to the Strict-Transport-Security header
traefik_headers_sts_subdomains: false
# Add preload flag appended to the Strict-Transport-Security header
traefik_headers_sts_preload: true
# Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
traefik_headers_sts_seconds: 63072000
traefik_https_skipVerify: false
traefik_ingress_ip: 10.10.10.11
traefik_log_access: false
traefik_log_level: INFO
traefik_log_format: common    # or json
traefik_name: "{{ k8s_namespace }}"
# -- Additional pod annotations (e.g. for mesh injection or prometheus scraping)
traefik_pod_annotations: { }
# -- Additional Pod labels (e.g. for filtering Pod by custom labels)
traefik_pod_labels: { }
traefik_replicas: 1
traefik_salt: ThisSaltMustBe22Chars.
traefik_send_usage: false
traefik_service_annotations: { }
traefik_service_labels: { }
